version: "3"
services:
  nginx:
    ports:
      - "81:80"
  moospire-server:
    build:
      context: .
      args:
        NODE_ENV: production
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    command: npm run serve:prod
