version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - moospire-frontend

  moospire-frontend:
    build:
      context: .
      dockerfile: Dockerfile
